### ISSUE TITLE
can't open on windows 10 with kivy 2.0.0

### ISSUE THREAD

**Issue by Eyedoljin** [Heitor-Tasso/KivyStudioDesigner#1]
1 - The project accept only the version of the packages on the requirements file, not the new versions
2- a sympy package is missing and i don't know if i get the right version for this project
3- error:
raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'profile'

**Comment by Heitor-Tasso** [comment]
I updated the requirements file and changed the code that has unusable libs, try to reinstall and see if it's working...

**Comment by smitht06** [comment]
Same issue here, i get the No Section: 'profile' on windows 10

**Comment by Heitor-Tasso** [comment]
I will see what is the problem, but now i'm very occupied...

**Comment by Heitor-Tasso** [comment]
Well, I solved this problem. Please try again and let me know if it's working now...
First delete a folder located in "roaming" -> C:\Users\Username\AppData\Roaming\programdesigner
